from __future__ import annotations
import io
from datetime import datetime
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
from .scoring import ScoreResult
from .plotting import render_percentages_bar


def generate_pdf(result: ScoreResult, output_path: str, author: str = "") -> None:
    c = canvas.Canvas(output_path, pagesize=landscape(letter))
    width, height = landscape(letter)

    c.setFont("Helvetica-Bold", 20)
    c.drawString(40, height - 50, "MBTI Personality Test Results")
    c.setFont("Helvetica", 12)
    c.drawString(40, height - 70, f"Type: {result.type}")
    c.drawString(40, height - 90, f"Author: {author or '—'}")
    c.drawString(40, height - 110, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")

    img_bytes = render_percentages_bar(result.percentages)
    img = ImageReader(io.BytesIO(img_bytes))
    c.drawImage(
        img,
        40,
        120,
        width=width - 80,
        height=height - 180,
        preserveAspectRatio=True,
        anchor="nw",
    )

    c.setFont("Helvetica-Oblique", 9)
    c.drawRightString(width - 40, 30, "Generated by mbti-cli")
    c.showPage()
    c.save()
